name: Node Actions CI

on: [ push, pull_request ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
        working-directory: ${{ env.working-directory }}
      - run: yarn test
        working-directory: ${{ env.working-directory }}
